<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ6fvoi4\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ6fvoi4/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZ6fvoi4.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZ6fvoi4\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZ6fvoi4\appProdProjectContainer([
    'container.build_hash' => 'Z6fvoi4',
    'container.build_id' => '30735623',
    'container.build_time' => 1678832211,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ6fvoi4');
